### ISSUE TITLE
promiseError disappeared?

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1705]
We still call `lib.promiseError` in [`lib.syncOrAsync`](https://github.com/plotly/plotly.js/blob/master/src/lib/index.js#L297) but it has disappeared? What do we want to have happen here?

**Comment by rreusser** [comment]
Is this similar to `fail_test.js`?

https://github.com/plotly/plotly.js/blob/master/test/jasmine/assets/fail_test.js

**Comment by etpinard** [comment]
From https://github.com/plotly/plotly.js/commit/7fa9243bd5005df988321d1bc730d5d3989bf63b#diff-e64ef427412e9bab4929b8b93ca12d96

**Comment by jklimke** [comment]
Hi, this came to my notice as i am receiving constantly warnings when using plotly in an promise based environment. As the promiseError function does not exist anymore, it should not be passed to promises for error handling as this causes a warning

```
Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]    at Object.push../node_modules/plotly.js/src/lib/index.js.lib.syncOrAsync (http://localhost:3000/packs/js/vendors~._node_modules_plotly.js_src_c-9f52df4a5f1ee8c919dc.chunk.js:3256:38)    at relayout (http://localhost:3000/packs/js/vendors~._node_modules_plotly.js_src_c-9f52df4a5f1ee8c919dc.chunk.js:10431:22)    at Object.push../node_modules/plotly.js/src/registry.js.exports.call (http://localhost:3000/packs/js/vendors~._node_modules_pl-6439151412dfacf8a22d.chunk.js:246:42)    at http://localhost:3000/packs/js/vendors~._node_modules_plotly.js_src_c-9f52df4a5f1ee8c919dc.chunk.js:28740:16
```

Deleting the line should not have side effects:

https://github.com/plotly/plotly.js/blob/e27ca3c691924b760a697f7176854cd91ae4dcd5/src/lib/index.js#L459

So please change it to the following code an leave error handling to the caller that provided a promise.
```
lib.syncOrAsync = function(sequence, arg, finalStep) {
    var ret, fni;

    function continueAsync() {
        return lib.syncOrAsync(sequence, arg, finalStep);
    }

    while(sequence.length) {
        fni = sequence.splice(0, 1)[0];
        ret = fni(arg);

        if(ret && ret.then) {
            return ret.then(continueAsync);
        }
    }

    return finalStep && finalStep(arg);
};
