### ISSUE TITLE
Unable to install on npm 5.0.0

### ISSUE THREAD

**Issue by jspath** [plotly/plotly.js#1745]
I updated npm to 5.0.0 and am now unable to install plotly.js.

I do not have this issue with npm 4.6.1

```
MBP15r-0G8WM:engagement jspath$ npm i plotly.js
npm WARN deprecated husl@5.0.3: Project renamed to HSLuv
npm WARN deprecated feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
npm WARN deprecated mapbox-gl-function@1.3.0: This package has been merged with the 'mapbox-gl-style-spec' package
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
npm WARN deprecated unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git clone --depth=1 -q -b 22/head git://github.com/mapbox/mapbox-gl-shaders.git /Users/jspath/.npm/_cacache/tmp/git-clone-391fb4fe
npm ERR! warning: templates not found /var/folders/mt/dzsls6454wv3db_j_djv3z5c0000gp/T/pacote-git-template-tmp/git-clone-b31dd07d
npm ERR! warning: Could not find remote branch 22/head to clone.
npm ERR! fatal: Remote branch 22/head not found in upstream origin
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jspath/.npm/_logs/2017-05-30T20_23_50_760Z-debug.log
```

The relevant section of the log file looks like:
```
1182 silly resolveWithNewModule mapbox-gl-style-spec@8.8.0 checking installable status
1183 verbose stack Error: Command failed: /usr/local/bin/git clone --depth=1 -q -b 22/head git://github.com/mapbox/mapbox-gl-shaders.git /Users/jspath/.npm/_cacache/tmp/git-clone-391fb4fe
1183 verbose stack warning: templates not found /var/folders/mt/dzsls6454wv3db_j_djv3z5c0000gp/T/pacote-git-template-tmp/git-clone-b31dd07d
1183 verbose stack warning: Could not find remote branch 22/head to clone.
1183 verbose stack fatal: Remote branch 22/head not found in upstream origin
1183 verbose stack
1183 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
1183 verbose stack     at emitTwo (events.js:106:13)
1183 verbose stack     at ChildProcess.emit (events.js:191:7)
1183 verbose stack     at maybeClose (internal/child_process.js:877:16)
1183 verbose stack     at Socket.<anonymous> (internal/child_process.js:334:11)
1183 verbose stack     at emitOne (events.js:96:13)
1183 verbose stack     at Socket.emit (events.js:188:7)
1183 verbose stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
1184 verbose cwd /Users/jspath/git/engagement
1185 verbose Darwin 16.6.0
1186 verbose argv "/Users/jspath/.nvm/versions/node/v6.9.2/bin/node" "/Users/jspath/.nvm/versions/node/v6.9.2/bin/npm" "i" "plotly.js"
1187 verbose node v6.9.2
1188 verbose npm  v5.0.0
1189 error code 128
1190 error Command failed: /usr/local/bin/git clone --depth=1 -q -b 22/head git://github.com/mapbox/mapbox-gl-shaders.git /Users/jspath/.npm/_cacache/tmp/git-clone-391fb4fe
1190 error warning: templates not found /var/folders/mt/dzsls6454wv3db_j_djv3z5c0000gp/T/pacote-git-template-tmp/git-clone-b31dd07d
1190 error warning: Could not find remote branch 22/head to clone.
1190 error fatal: Remote branch 22/head not found in upstream origin
1191 verbose exit [ 1, true ]
```

**Comment by etpinard** [comment]
Looks like it's a problem with `mapbox-gl`. Not much we can do here until with resolve https://github.com/plotly/plotly.js/issues/1714

**Comment by etpinard** [comment]
Reopening.

`npm@5` is now npm's `latest` version. It ships with Node 8. Even though #1714 seems to be the one and only culprit, getting plotly.js to install properly in `npm@5` deserves a ticket of its own.

Thanks @jspath for bringing this up.

**Comment by etpinard** [comment]
Similar problems have been reported to npm: https://github.com/npm/npm/issues/16830#issuecomment-305311679

**Comment by etpinard** [comment]
Something like

**Comment by etpinard** [comment]
Update: this is still an issue with `npm@5.0.2`. We'll have to go through with #1752 in the next release `1.28.0`.

**Comment by aliavni** [comment]
I have the same issue here

**Comment by zkat** [comment]
This should be alright as of `npm@5.0.3`, btw

**Comment by etpinard** [comment]
Thanks so much @zkat :tada: 

`npm i plotly.js` now works with `npm@5.0.3` 

Thank you for your hard work :+1: 

----

So, to anyone having issue installing plotly.js with `npm@5`, running `npm i -g npm` should fix that. Closing this and closing https://github.com/plotly/plotly.js/pull/1752

**Comment by v1r0x** [comment]
I have the exact same error using npm 5.5.1. Is this a known problem or anything I can do to fix this?

**Comment by etpinard** [comment]
@v1r0x would you mind giving a bit more info? I was able to `npm i plotly.js` successfully with npm 5.5.1.

**Comment by v1r0x** [comment]
@etpinard Sorry, forgot to mention that it's the same as OP. But here is my output:
```bash
me@bowmore:/home/me$ LANG=C npm i plotly.js
npm WARN deprecated husl@5.0.3: Project renamed to HSLuv
npm WARN deprecated feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
npm WARN deprecated mapbox-gl-function@1.3.0: This package has been merged with the 'mapbox-gl-style-spec' package
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
npm WARN deprecated unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b 22/head git://github.com/mapbox/mapbox-gl-shaders.git /home/me/.npm/_cacache/tmp/git-clone-36b47657
npm ERR! warning: templates not found /tmp/pacote-git-template-tmp/git-clone-ca33ed2f
npm ERR! warning: Could not find remote branch 22/head to clone.
npm ERR! fatal: Remote branch 22/head not found in upstream origin
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2017-11-17T15_18_14_989Z-debug.log
```

**Comment by etpinard** [comment]
@v1r0x have you looked into https://github.com/plotly/plotly.js/issues/2104#issuecomment-337939610 ?

**Comment by v1r0x** [comment]
@etpinard Yes, but that didn't work. I use npm in a git repo and I'm connected to github with ssh. I removed my `known_hosts`, but still the same error. Did I miss something from #2104 ?
