### ISSUE TITLE
newPlot errs with Pie + textinfo: "text" 

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/plotly.js#2179]
https://codepen.io/bpostlethwaite/pen/ZaxJvR
```javascript
var data = [{
  values: [27, 11, 25],
  labels: ['US', 'China', 'European Union'],
  textinfo: 'text',
  type: 'pie'
}];

Plotly.newPlot('myDiv', data);
```
errors with
```
Uncaught TypeError: Cannot read property '0' of undefined
    at Object.e.exports [as calc] (https://cdn.plot.ly/plotly-latest.min.js:75:11043)
    at Object.g.doCalcdata (https://cdn.plot.ly/plotly-latest.min.js:67:14762)
    at Object._.plot (https://cdn.plot.ly/plotly-latest.min.js:60:6151)
    at Object._.newPlot (https://cdn.plot.ly/plotly-latest.min.js:60:6846)
    at pen.js:20:8
```

The feature still works if there is text data in the plot. If you remove trace text but leave the text flag in `textinfo` you get the error.

**Comment by etpinard** [comment]
It seems to be fixed on `master`.

**Comment by etpinard** [comment]
I'm getting 

![image](https://user-images.githubusercontent.com/6675409/33089797-c43c1112-cebf-11e7-858a-9098ad3b8807.png)


with no errors.

**Comment by bpostlethwaite** [comment]
easy fix then :)
