### ISSUE TITLE
Error installing via npm: npm ERR! 404 Not Found: @plotly/d3-sankey@^0.5.0 

### ISSUE THREAD

**Issue by sid-thakur** [plotly/plotly.js#2686]
Installation error: Getting following error while installing plotly.js via npm:
```
$ npm install plotly.js
npm ERR! code E404
npm ERR! 404 Not Found: @plotly/d3-sankey@^0.5.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abc/.npm/_logs/2018-05-31T13_52_57_384Z-debug.log
```
Environment:
```
# OS: Mac OSX 10.11.6
# d3 v4

$ node --version
v8.9.1
$ npm --version
5.7.a

```

**Comment by etpinard** [comment]
I can't reproduce on Ubuntu 16.04

**Comment by sid-thakur** [comment]
Thanks @etpinard 

Here's a more detailed log trace:
```
185 verbose stack Error: 404 Not Found: @plotly/d3-sankey@^0.5.0
185 verbose stack     at fetch.then.res (/Users/abc/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
185 verbose stack     at tryCatcher (/Users/abc/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
185 verbose stack     at Promise._settlePromiseFromHandler (/Users/abc/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
185 verbose stack     at Promise._settlePromise (/Users/abc/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
185 verbose stack     at Promise._settlePromise0 (/Users/abc/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
185 verbose stack     at Promise._settlePromises (/Users/abc/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
185 verbose stack     at Async._drainQueue (/Users/abc/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
185 verbose stack     at Async._drainQueues (/Users/abc/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
185 verbose stack     at Immediate.Async.drainQueues (/Users/abc/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
185 verbose stack     at runCallback (timers.js:789:20)
185 verbose stack     at tryOnImmediate (timers.js:751:5)
185 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
186 verbose cwd /Users/abc/src/DSE/dse-flask-app/static
187 verbose Darwin 15.6.0
188 verbose argv "/Users/abc/.nvm/versions/node/v8.9.1/bin/node" "/Users/abc/.nvm/versions/node/v8.9.1/bin/npm" "i" "plotly.js"
189 verbose node v8.9.1
190 verbose npm  v5.7.1
191 error code E404
192 error 404 Not Found: @plotly/d3-sankey@^0.5.0
193 verbose exit [ 1, true ]
```

**Comment by alexcjohnson** [comment]
I also can't reproduce - I can delete and reinstall `@plotly/d3-sankey` v0.5.0 with no errors.
OS X 10.13.4 with node 8.9.4, npm 5.8.0

I don't see how it would cause such a problem, but note plotly.js uses d3 v3 still - and we've seen it cause occasional problems in the front end if both v3 and v4 (or 5) are loaded in one page - see eg https://github.com/plotly/plotly-webpack/issues/5

**Comment by sid-thakur** [comment]
Resolved; re-tried `npm install plotly.js` a few times; likely an issue with my proxy settings.
