### ISSUE TITLE
Cannot read property 'hoverinfo' of undefined

### ISSUE THREAD

**Issue by UshaNandhini28** [plotly/plotly.js#5573]
Cannot read property 'hoverinfo' of undefined TypeError: Cannot read property 'hoverinfo' of undefined
    at o.t.onHover (http://localhost:8081/widgets/com/mendix/widget/custom/AnyChart/AnyChart.js?637527832920940092:17:2624)
    at http://localhost:8081/widgets/com/mendix/widget/custom/AnyChart/chunke67f90a80138c9981a69.js:1:134798
    at o.emit (http://localhost:8081/widgets/com/mendix/widget/custom/AnyChart/chunke67f90a80138c9981a69.js:1:134868)
    at HTMLDivElement.t.emit (http://localhost:8081/widgets/com/mendix/widget/custom/AnyChart/chunke67f90a80138c9981a69.js:1:2142415)
    at Object.hover (http://localhost:8081/widgets/com/mendix/widget/custom/AnyChart/chunke67f90a80138c9981a69.js:1:3004824)
    at SVGPathElement.<anonymous> (http://localhost:8081/widgets/com/mendix/widget/custom/AnyChart/chunke67f90a80138c9981a69.js:1:3013317)
    at SVGPathElement.__onmouseover.basic (http://localhost:8081/widgets/com/mendix/widget/custom/AnyChart/chunke67f90a80138c9981a69.js:1:316835)

**Comment by alexcjohnson** [comment]
I gather we're talking about the [Mendix Any Chart widget](https://docs.mendix.com/appstore/modules/any-chart). That appears to be based on Plotly.js v1.47.4, which is nearly two years old, so this bug may already have been fixed, and if not I'm not sure what the process will be to update that widget. Nevertheless if you can recreate the problem in plain plotly.js in a codepen, like https://codepen.io/alexcjohnson/pen/OJbGMMo we'd be happy to take a look. Note that you can replace `plotly-latest.min.js` with `plotly-1.47.4.min.js` to test the same version as in that Mendix widget.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
